# Application Name
spring.application.name=MobileStore

# Dynamic Environment Variables with Safe Empty Defaults
google.client.id=${GOOGLE_CLI_ID:}
frontend.url=${FRONTEND_URL:http://localhost:5173}

# Spring Datasource Configuration (Render / Local Override-ku)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mobile_shop}
spring.datasource.username=${DB_USER:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# Server Configuration
server.port=${PORT:8080}

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security Logging
logging.level.org.springframework.security=DEBUG

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect