# Application Name
spring.application.name=MobileStore

google.client.id=${GOOGLE_CLI_ID:1049963241178-osdmpvpj2hv61nnsltf8vq5b7iqojfmr.apps.googleusercontent.com}
frontend.url=${FRONTEND_URL:http://localhost:5173}

# Added jdbc: prefix fallback handling
spring.datasource.url=jdbc:${DB_URL:postgresql://localhost:5432/mobile_shop}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:Cloud@123}
server.port=${PORT:8080}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG