google.client.id=1049963241178-osdmpvpj2hv61nnsltf8vq5b7iqojfmr.apps.googleusercontent.com

# Application Name
spring.application.name=MobileStore
spring.datasource.url=jdbc:postgresql://localhost:5432/mobile_shop
spring.datasource.username=postgres
spring.datasource.password=Cloud@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect